warining_size: 505 # 警告容量大小，单位：GB
pause_size: 100 # 停止搬运程序大小，单位：GB
alerty_type: email #通知类型，目前仅支持email和dingtalk
email:
  host: smtp.xxx.com
  port: 547
  username: username
  password: password
  to:
    - abc@xx.com
    - cde@xx.com
dingtalk:
  url: https://oapi.dingtalk.com/robot/send?access_token=XXXXXX